theme: jekyll-theme-cayman
url: "https://defghy.github.io" # the base hostname & protocol for your site
plugins:
  - jekyll-sitemap
  - jekyll-last-modified-at
defaults:
  -
    scope:
      path: "defghy/**/*.*"
    values:
      sitemap: false
  - 
    scope:
      path: "google7d2ed205f6bf437f*"
    values:
      sitemap: false